import type { ThemeConfig } from 'antd';

const antdMobileTheme: ThemeConfig = {
  cssVar: {
    prefix: PREFIX_NAME,
  },
  hashed: false,
  token: {
    borderRadius: 10,
    colorSuccess: '#00b42a',
    colorWarning: '#ff7d00',
    colorText: '#14161a',
    colorTextSecondary: '#40454d',
    colorTextTertiary: '#707680',
    colorTextQuaternary: '#a4aab2',
    colorBorder: '#00000026',
    colorBorderSecondary: '#0000000f',
    colorFillQuaternary: '#00000005',
    colorFillTertiary: '#0000000a',
    colorFillSecondary: '#0000000f',
    colorFill: '#00000026',
    borderRadiusSM: 8,
    borderRadiusXS: 6,
    colorPrimary: '#165dff',
    colorInfo: '#165dff',
    colorError: '#f53f3f',
    fontSizeXL: 18,
    fontSizeHeading2: 32,
    colorPrimaryBg: '#e8f3ff',
    colorPrimaryBgHover: '#bedaff',
    colorPrimaryBorder: '#94bfff',
    colorPrimaryBorderHover: '#6aa1ff',
    colorPrimaryHover: '#4080ff',
    colorPrimaryActive: '#0e42d2',
    colorPrimaryTextActive: '#0e42d2',
    colorPrimaryText: '#165dff',
    colorPrimaryTextHover: '#4080ff',
    colorSuccessBg: '#e8ffea',
    colorSuccessBgHover: '#aff0b5',
    colorSuccessBorder: '#7be188',
    colorSuccessBorderHover: '#4cd263',
    colorSuccessHover: '#23c343',
    colorSuccessActive: '#009a29',
    colorSuccessTextActive: '#009a29',
    colorSuccessTextHover: '#23c343',
    colorSuccessText: '#00b42a',
    colorWarningBg: '#fff7e8',
    colorWarningBgHover: '#ffe4ba',
    colorWarningBorder: '#ffcf8b',
    colorWarningBorderHover: '#ffb65d',
    colorWarningHover: '#ff9a2e',
    colorWarningTextHover: '#ff9a2e',
    colorWarningText: '#ff7d00',
    colorWarningActive: '#d25f00',
    colorWarningTextActive: '#d25f00',
    colorErrorText: '#f53f3f',
    colorErrorBg: '#ffece8',
    colorErrorBgHover: '#fdcdc5',
    colorErrorBorder: '#fbaca3',
    colorErrorBorderHover: '#f98981',
    colorErrorHover: '#f76560',
    colorErrorTextHover: '#f76560',
    colorErrorActive: '#cb272d',
    colorErrorTextActive: '#cb272d',
    colorBgSpotlight: '#000000e6',
    colorBgMask: '#00000080',
  },
  components: {
    Select: {
      fontSize: 12,
    },
    Button: {
      fontSize: 12,
      paddingBlock: 2,
      paddingInline: 8,
    },
    Space: {
      padding: 8,
      paddingLG: 12,
      paddingXS: 4,
    },
    Tabs: {
      colorBorderSecondary: 'rgba(230,235,240,0)',
    },
    Anchor: {
      colorSplit: 'rgba(5,55,105,0)',
    },
    Table: {
      algorithm: true,
      headerBg: 'rgb(255,255,255)',
      headerColor: 'rgb(122,135,153)',
      cellPaddingBlock: 15,
      cellPaddingInline: 15,
      fontWeightStrong: 0,
    },
    Checkbox: {
      borderRadiusSM: 4,
    },
    Layout: {
      siderBg: 'rgb(242,246,250)',
    },
  },
};

export default antdMobileTheme;
