export const JSON_INDENT_SPACES = 2;

export const PACKAGE = {
  pluginId: "byclaw-acp-adapter",
  nodeTarget: "node22",
  version: "2026.6.29",
};

export const ENV = {
  openclawRoot: "OPENCLAW_ROOT",
  openclawTemplatePath: "OPENCLAW_TEMPLATE_PATH",
  openclawGatewayPort: "OPENCLAW_GATEWAY_PORT",
  openclawGatewayToken: "OPENCLAW_GATEWAY_TOKEN",
  openclawStateDir: "OPENCLAW_STATE_DIR",
  openclawConfigPath: "BYCLAW_OPENCLAW_TEST_CONFIG",
  openclawExtensionTarget: "OPENCLAW_EXTENSION_TARGET",
  byclawOpenclawUsePackagedCli: "BYCLAW_OPENCLAW_USE_PACKAGED_CLI",
  byclawExtensionTarget: "BYCLAW_ACP_ADAPTER_OPENCLAW_TARGET",
  byclawAcpClaudeModel: "BYCLAW_ACP_CLAUDE_MODEL",
  byclawAcpClaudeModelId: "BYCLAW_ACP_CLAUDE_MODEL_ID",
  byclawAcpClaudeAnthropicBaseUrl: "BYCLAW_ACP_CLAUDE_ANTHROPIC_BASE_URL",
  byclawAcpKeepAnthropicApiKey: "BYCLAW_ACP_KEEP_ANTHROPIC_API_KEY",
  byclawAcpStrongModel: "BYCLAW_ACP_CLAUDE_STRONG_MODEL",
  byclawAcpAgentId: "BYCLAW_ACP_AGENT_ID",
  byclawAcpUseRemoteClaude: "BYCLAW_ACP_USE_REMOTE_CLAUDE",
  byclawAcpRemoteClaudeAgentId: "BYCLAW_ACP_REMOTE_CLAUDE_AGENT_ID",
  byclawAcpRemoteClaudeCommand: "BYCLAW_ACP_REMOTE_CLAUDE_COMMAND",
  byclawDigEmployeeOwnerType: "BYCLAW_DIG_EMPLOYEE_OWNER_TYPE",
  byclawDigEmployeeAgentType: "BYCLAW_DIG_EMPLOYEE_AGENT_TYPE",
  byclawDigEmployeeFrontAccess: "BYCLAW_DIG_EMPLOYEE_FRONT_ACCESS",
  anthropicModel: "ANTHROPIC_MODEL",
  redisHost: "REDIS_HOST",
  redisPort: "REDIS_PORT",
  redisUsername: "REDIS_USERNAME",
  redisPassword: "REDIS_PASSWORD",
  redisDatabase: "REDIS_DATABASE",
  byclawSmokeAcpStreamTimeoutMs: "BYCLAW_SMOKE_ACP_STREAM_TIMEOUT_MS",
  byclawSmokePrintGatewayLog: "BYCLAW_SMOKE_PRINT_GATEWAY_LOG",
};

export const DEFAULTS = {
  openclawRoot: "",
  gatewayHost: "127.0.0.1",
  gatewayPort: 18789,
  gatewayToken: "byclaw-acp-test-token",
  acpAgentId: "claude",
  remoteClaudeAgentId: "byclaw-remote-claude",
  claudeModel: "anthropic/sonnet",
  syncRuntimeModel: "MiniMax-M3",
  syncApiBaseUrl: "http://10.10.168.204:8080",
  syncUserCode: "0027024710",
  syncLanguage: "zh-CN",
  syncOwnerType: "enterprise",
  syncAgentType: "001",
  redisHost: "127.0.0.1",
  redisPort: 6379,
  redisDatabase: 0,
  redisConnectTimeoutMs: 5000,
  pluginRedisConnectTimeoutMs: 5000,
  gatewayReadyTimeoutMs: 60000,
  gatewayPollIntervalMs: 1500,
  gatewayRequestTimeoutMs: 30000,
  gatewaySocketOpenTimeoutMs: 10000,
  gatewayConnectRequestTimeoutMs: 15000,
  acpStreamTimeoutMs: 120000,
  sessionsSpawnInvokeTimeoutMs: 180000,
  sessionsSpawnRetryCount: 8,
  sessionsSpawnRetryDelayMs: 2500,
  gatewayShutdownGraceMs: 1000,
  smokeStreamTailLines: 5,
  smokeSampledEventLimit: 10,
  smokeMinimumAgentCount: 9,
  smokeMinimumTaskCount: 7,
  protocolVersion: 4,
  aimodelResolverProtocolVersion: 1,
  wrapperModelId: "10002933",
  wrapperAnthropicBaseUrl: "https://api.minimaxi.com/anthropic",
  modelTemperature: 0.1,
  fixtureRedisConnectTimeoutMs: 1000,
  baiyingWatchDebounceMs: 500,
};

export const PATHS = {
  tempDir: ".tmp",
  testConfigFileName: "openclaw-byclaw-acp-test.json",
  stateDirName: "openclaw-state",
  openclawTemplateFileName: "openclaw_template.json",
  logsDir: "logs",
  openclawLogFileName: "openclaw.log",
  acpxStateDir: "acpx",
  workspaceDir: "workspace",
  pluginStateDir: "byclaw-acp-adapter",
  pluginSqliteFileName: "byclaw-acp-adapter.sqlite",
  byclawDir: ".byclaw",
  acpRunsDir: "acp-runs",
  clientDirNames: {
    claudeCode: "claudeCode",
    codex: "codex",
  },
  wrapperRelativePath:
    "byclaw-exe/extensions/byclaw-acp-adapter/scripts/claude-agent-acp-baiying-wrapper.mjs",
  remoteClaudeBridgeRelativePath:
    "byclaw-exe/extensions/byclaw-acp-adapter/scripts/byclaw-remote-claude-acp.mjs",
  extensions: {
    baiyingEnhance: "byclaw-exe/extensions/baiying-enhance",
    byaiChannel: "byclaw-exe/extensions/byai-channel",
    byclawSqlite: "byclaw-exe/extensions/byclaw-sqlite",
    byclawAcpAdapter: "byclaw-exe/extensions/byclaw-acp-adapter",
    acpx: "extensions/acpx",
  },
  claudeAgentAcpBin: [
    "node_modules",
    "@agentclientprotocol",
    "claude-agent-acp",
    "dist",
    "index.js",
  ],
  resolverCli: ["baiying-enhance", "dist", "aimodel-secret-resolver-cli.js"],
  testBundlesDir: [".tmp", "test-bundles"],
  plannerBundleFileName: "planner.bundle.mjs",
  sessionsSpawnPayloadWorkspace: "byclaw-acp-adapter-sessions-spawn-payload",
  defaultOpenclawRootParts: ["..", "open", "openclaw"],
};

export const HTTP = {
  scheme: "http",
  wsScheme: "ws",
  methods: {
    get: "GET",
    post: "POST",
  },
  headers: {
    authorization: "Authorization",
    contentType: "content-type",
  },
  contentTypes: {
    json: "application/json",
  },
};

export const GATEWAY = {
  backend: "acpx",
  bind: "lan",
  mode: "local",
  authMode: "token",
  tokenPlaceholder: "${OPENCLAW_GATEWAY_TOKEN}",
  mainAgentId: "main",
  backendMode: "backend",
  operatorRole: "operator",
  clientId: "gateway-client",
  clientDisplayName: "ByClaw ACP adapter smoke",
  instanceId: "byclaw-acp-adapter-smoke",
  userAgent: "byclaw-acp-adapter-smoke",
  locale: "zh-CN",
  scopes: [
    "operator.admin",
    "operator.read",
    "operator.write",
    "operator.approvals",
    "operator.pairing",
    "operator.talk.secrets",
  ],
  caps: ["tool-events"],
  tools: {
    sessionsSpawn: "sessions_spawn",
    applyPatch: "apply_patch",
    exec: "exec",
    spawn: "spawn",
    shell: "shell",
    fsWrite: "fs_write",
    fsDelete: "fs_delete",
    fsMove: "fs_move",
  },
  rpc: {
    connect: "connect",
    toolsInvoke: "tools.invoke",
  },
  frameTypes: {
    request: "req",
    response: "res",
    event: "event",
  },
};

export const OPENCLAW_PLUGINS = {
  acpx: "acpx",
  byclawAcpAdapter: "byclaw-acp-adapter",
  byclawSqlite: "byclaw-sqlite",
  baiyingEnhance: "baiying-enhance",
  byaiChannel: "byai-channel",
};

export const REDIS_KEYS = {
  digitalEmployeePrefix: "DIG_EMPLOYEE_",
  digitalEmployeePattern: "DIG_EMPLOYEE_*",
  skillPrefix: "SKILL_",
  teamPrefix: "BYCLAW_AGENT_TEAM_",
  workflowPrefix: "BYCLAW_WORKFLOW_",
  loopPrefix: "BYCLAW_LOOP_",
  userResourcesAuthPrefix: "USER:RESOURCES:AUTH",
  digitalEmployeeChangeChannel: "byai:pub:dig_employee_change",
  aimodelConfig: "byai:aimodel:config",
  aimodelTypeList: "byai:aimodel:typelist",
  typeListLlmField: "LLM",
  authorizedValue: "1",
};

export const ACP = {
  runtime: "acp",
  nativeSubagentsRuntime: "claude-code-native-subagents",
  streamTo: "parent",
  mode: "run",
  providerClaudeCode: "claude-code-acp",
  providerAnthropicCompatible: "anthropic-compatible",
};
