package com.iwhalecloud.byai.gateway.channels.service.wecom.sdk;

import org.junit.jupiter.api.Test;

import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Task 7 crypto verification. Fixtures are generated by encrypting with the
 * SAME rule the WeCom SDK uses (AES-256-CBC/NoPadding, IV = first 16 bytes of
 * the key, PKCS#7 padded to a 32-byte multiple), then asserting
 * {@link WecomFileCrypto#decrypt} recovers the plaintext exactly.
 */
class WecomFileCryptoTest {

    /** 32-byte key, base64-encoded, as WeCom delivers aeskey. */
    private static String makeAesKeyBase64() {
        byte[] key = new byte[32];
        for (int i = 0; i < 32; i++) {
            key[i] = (byte) (i * 7 + 3);
        }
        return Base64.getEncoder().encodeToString(key);
    }

    /** Encrypt with WeCom's scheme: NoPadding + manual PKCS#7 to a 32-byte multiple. */
    private static byte[] encryptWecomStyle(byte[] plain, String aesKeyBase64) throws Exception {
        byte[] key = Base64.getDecoder().decode(aesKeyBase64);
        byte[] iv = Arrays.copyOfRange(key, 0, 16);

        int block = 32;
        int padLen = block - (plain.length % block);
        if (padLen == 0) {
            padLen = block;
        }
        byte[] padded = Arrays.copyOf(plain, plain.length + padLen);
        for (int i = plain.length; i < padded.length; i++) {
            padded[i] = (byte) padLen;
        }

        Cipher cipher = Cipher.getInstance("AES/CBC/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(key, "AES"), new IvParameterSpec(iv));
        return cipher.doFinal(padded);
    }

    @Test
    void roundTripSmallPayload() throws Exception {
        String key = makeAesKeyBase64();
        byte[] plain = "hello wecom 你好".getBytes(StandardCharsets.UTF_8);
        byte[] encrypted = encryptWecomStyle(plain, key);

        byte[] decrypted = WecomFileCrypto.decrypt(encrypted, key);
        assertThat(decrypted).isEqualTo(plain);
    }

    @Test
    void roundTripExactBlockMultipleAddsFullPadBlock() throws Exception {
        String key = makeAesKeyBase64();
        // 32 bytes exactly -> a full 32-byte pad block is appended, must survive.
        byte[] plain = new byte[32];
        Arrays.fill(plain, (byte) 'A');
        byte[] encrypted = encryptWecomStyle(plain, key);

        byte[] decrypted = WecomFileCrypto.decrypt(encrypted, key);
        assertThat(decrypted).isEqualTo(plain);
    }

    @Test
    void roundTripLargerBinaryPayload() throws Exception {
        String key = makeAesKeyBase64();
        byte[] plain = new byte[1000];
        for (int i = 0; i < plain.length; i++) {
            plain[i] = (byte) (i % 256);
        }
        byte[] encrypted = encryptWecomStyle(plain, key);

        byte[] decrypted = WecomFileCrypto.decrypt(encrypted, key);
        assertThat(decrypted).isEqualTo(plain);
    }

    @Test
    void rejectsNon32ByteKey() {
        // 16-byte key base64 -> must be rejected (WeCom uses AES-256).
        String shortKey = Base64.getEncoder().encodeToString(new byte[16]);
        assertThatThrownBy(() -> WecomFileCrypto.decrypt(new byte[32], shortKey))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("32 bytes");
    }

    @Test
    void rejectsEmptyPayloadAndBlankKey() {
        assertThatThrownBy(() -> WecomFileCrypto.decrypt(new byte[0], makeAesKeyBase64()))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> WecomFileCrypto.decrypt(new byte[32], ""))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void removePkcs7RejectsOutOfRangePad() {
        byte[] badHigh = new byte[32];
        badHigh[31] = (byte) 33; // > 32, invalid for WeCom range
        assertThatThrownBy(() -> WecomFileCrypto.removePkcs7Padding(badHigh))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Invalid PKCS#7 padding value");

        byte[] badZero = new byte[32]; // last byte 0 -> invalid
        assertThatThrownBy(() -> WecomFileCrypto.removePkcs7Padding(badZero))
                .isInstanceOf(IllegalStateException.class);
    }

    @Test
    void removePkcs7RejectsMismatchedPadBytes() {
        byte[] data = new byte[10];
        // claim pad length 3 but the three trailing bytes are not all 3
        data[9] = 3;
        data[8] = 3;
        data[7] = 1;
        assertThatThrownBy(() -> WecomFileCrypto.removePkcs7Padding(data))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("padding bytes mismatch");
    }

    @Test
    void removePkcs7AcceptsMaxPad32() {
        byte[] data = new byte[32];
        Arrays.fill(data, (byte) 32); // entire block is padding
        byte[] out = WecomFileCrypto.removePkcs7Padding(data);
        assertThat(out).isEmpty();
    }
}
