package com.iwhalecloud.byai.state.domain.resource.dto;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

import com.iwhalecloud.byai.state.domain.resource.utils.LongToStringSerializer;
import lombok.Data;

@Data
public class AgtResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.resource_id
     *
     * @mbggenerated
     */
    @JSONField(serializeUsing = LongToStringSerializer.class)
    private Long resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.resource_name
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.resource_type
     *
     * @mbggenerated
     */
    private Integer resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.obj_id
     * @mbggenerated
     */
    @JSONField(serializeUsing = LongToStringSerializer.class)
    private Long objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.catalog_id
     *
     * @mbggenerated
     */
    private Long catalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.create_user
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.update_user
     *
     * @mbggenerated
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.is_deleted
     *
     * @mbggenerated
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.remark
     *
     * @mbggenerated
     */
    private String remark;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.default_resource_icon
     *
     * @mbggenerated
     */
    private String defaultResourceIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.resource_project_id
     *
     * @mbggenerated
     */
    private Long resourceProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_resource.resource_logo_url
     *
     * @mbggenerated
     */
    private String resourceLogoUrl;


    private Long sort;
}