package com.iwhalecloud.byai.state.domain.agent.model;

import java.util.Date;

/**
 * 超级助手子智能体关联实体类
 * 
 * 该类用于表示超级助手与子智能体之间的关联关系。
 * 主要用于管理超级助手关注的智能体列表，支持智能体的关注、取消关注等操作。
 * 
 * 数据库表：suas_superassist_sub_agent
 * 
 * @author MyBatis Generator
 * @version 1.0
 * @date 2025/4/26
 */
public class SuasSuperassistSubAgent {
    /**
     * 超级助手子智能体关联ID
     * 
     * 该字段是主键，用于唯一标识超级助手与子智能体的关联关系记录。
     * 
     * 数据库字段：suas_superassist_sub_agent.superassist_sub_agent_id
     *
     * @mbggenerated
     */
    private Long superassistSubAgentId;

    /**
     * 超级助手ID
     * 
     * 该字段表示超级助手的唯一标识，用于关联具体的超级助手用户。
     * 
     * 数据库字段：suas_superassist_sub_agent.superassist_id
     *
     * @mbggenerated
     */
    private Long superassistId;

    /**
     * 智能体ID
     * 
     * 该字段表示被关注的智能体的唯一标识，用于关联具体的数字员工或智能体。
     * 
     * 数据库字段：suas_superassist_sub_agent.agent_id
     *
     * @mbggenerated
     */
    private Long agentId;

    /**
     * 创建人ID
     * 
     * 该字段记录创建此关联关系的用户ID，用于审计和追踪。
     * 
     * 数据库字段：suas_superassist_sub_agent.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * 更新人ID
     * 
     * 该字段记录最后更新此关联关系的用户ID，用于审计和追踪。
     * 
     * 数据库字段：suas_superassist_sub_agent.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;

    /**
     * 更新时间
     * 
     * 该字段记录此关联关系的最后更新时间，用于数据同步和审计。
     * 
     * 数据库字段：suas_superassist_sub_agent.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * 企业账户ID
     * 
     * 该字段表示所属的企业账户ID，用于多租户隔离和数据权限控制。
     * 
     * 数据库字段：suas_superassist_sub_agent.com_acct_id
     *
     * @mbggenerated
     */
    private Long comAcctId;

    /**
     * 创建时间
     * 
     * 该字段记录此关联关系的创建时间，用于数据审计和业务分析。
     * 
     * 数据库字段：suas_superassist_sub_agent.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 是否置顶
     * 
     * 该字段用于表示该子智能体是否被置顶，1 表示置顶，0 表示未置顶。
     * 
     * 数据库字段：suas_superassist_sub_agent.is_top
     *
     * @mbggenerated
     */
    private Integer isTop;

    /**
     * 置顶时间
     * 
     * 该字段记录被置顶的时间，用于排序或过期处理。
     * 
     * 数据库字段：suas_superassist_sub_agent.top_time
     *
     * @mbggenerated
     */
    private Date topTime;

    /**
     * 智能体类型
     * 
     * 用于标识关联的智能体类型，例如：数字员工、知识库、技能等。
     * 
     * 数据库字段：suas_superassist_sub_agent.agent_type
     *
     * @mbggenerated
     */
    private String agentType;

    /**
     * 是否订阅
     * 
     * 1 表示已订阅，0 表示未订阅。
     * 
     * 数据库字段：suas_superassist_sub_agent.is_sub
     *
     * @mbggenerated
     */
    private Integer isSub;

    /**
     * 订阅时间
     * 
     * 记录订阅发生的时间。
     * 
     * 数据库字段：suas_superassist_sub_agent.sub_time
     *
     * @mbggenerated
     */
    private Date subTime;

    /**
     * 状态编码
     * 
     * 记录关联的状态编码。
     * 
     * 数据库字段：suas_superassist_sub_agent.status_cd
     *
     * @mbggenerated
     */
    private String statusCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.superassist_sub_agent_id
     *
     * @return the value of suas_superassist_sub_agent.superassist_sub_agent_id
     *
     * @mbggenerated
     */
    public Long getSuperassistSubAgentId() {
        return superassistSubAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.superassist_sub_agent_id
     *
     * @param superassistSubAgentId the value for suas_superassist_sub_agent.superassist_sub_agent_id
     *
     * @mbggenerated
     */
    public void setSuperassistSubAgentId(Long superassistSubAgentId) {
        this.superassistSubAgentId = superassistSubAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.superassist_id
     *
     * @return the value of suas_superassist_sub_agent.superassist_id
     *
     * @mbggenerated
     */
    public Long getSuperassistId() {
        return superassistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.superassist_id
     *
     * @param superassistId the value for suas_superassist_sub_agent.superassist_id
     *
     * @mbggenerated
     */
    public void setSuperassistId(Long superassistId) {
        this.superassistId = superassistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.agent_id
     *
     * @return the value of suas_superassist_sub_agent.agent_id
     *
     * @mbggenerated
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.agent_id
     *
     * @param agentId the value for suas_superassist_sub_agent.agent_id
     *
     * @mbggenerated
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.create_by
     *
     * @return the value of suas_superassist_sub_agent.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.create_by
     *
     * @param createBy the value for suas_superassist_sub_agent.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.update_by
     *
     * @return the value of suas_superassist_sub_agent.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.update_by
     *
     * @param updateBy the value for suas_superassist_sub_agent.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.update_date
     *
     * @return the value of suas_superassist_sub_agent.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.update_date
     *
     * @param updateDate the value for suas_superassist_sub_agent.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.com_acct_id
     *
     * @return the value of suas_superassist_sub_agent.com_acct_id
     *
     * @mbggenerated
     */
    public Long getComAcctId() {
        return comAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.com_acct_id
     *
     * @param comAcctId the value for suas_superassist_sub_agent.com_acct_id
     *
     * @mbggenerated
     */
    public void setComAcctId(Long comAcctId) {
        this.comAcctId = comAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.create_time
     *
     * @return the value of suas_superassist_sub_agent.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.create_time
     *
     * @param createTime the value for suas_superassist_sub_agent.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.is_top
     *
     * @return the value of suas_superassist_sub_agent.is_top
     *
     * @mbggenerated
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.is_top
     *
     * @param isTop the value for suas_superassist_sub_agent.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.top_time
     *
     * @return the value of suas_superassist_sub_agent.top_time
     *
     * @mbggenerated
     */
    public Date getTopTime() {
        return topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.top_time
     *
     * @param topTime the value for suas_superassist_sub_agent.top_time
     *
     * @mbggenerated
     */
    public void setTopTime(Date topTime) {
        this.topTime = topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.agent_type
     *
     * @return the value of suas_superassist_sub_agent.agent_type
     *
     * @mbggenerated
     */
    public String getAgentType() {
        return agentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.agent_type
     *
     * @param agentType the value for suas_superassist_sub_agent.agent_type
     *
     * @mbggenerated
     */
    public void setAgentType(String agentType) {
        this.agentType = agentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.is_sub
     *
     * @return the value of suas_superassist_sub_agent.is_sub
     *
     * @mbggenerated
     */
    public Integer getIsSub() {
        return isSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.is_sub
     *
     * @param isSub the value for suas_superassist_sub_agent.is_sub
     *
     * @mbggenerated
     */
    public void setIsSub(Integer isSub) {
        this.isSub = isSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.sub_time
     *
     * @return the value of suas_superassist_sub_agent.sub_time
     *
     * @mbggenerated
     */
    public Date getSubTime() {
        return subTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.sub_time
     *
     * @param subTime the value for suas_superassist_sub_agent.sub_time
     *
     * @mbggenerated
     */
    public void setSubTime(Date subTime) {
        this.subTime = subTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suas_superassist_sub_agent.status_cd
     *
     * @return the value of suas_superassist_sub_agent.status_cd
     *
     * @mbggenerated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suas_superassist_sub_agent.status_cd
     *
     * @param statusCd the value for suas_superassist_sub_agent.status_cd
     *
     * @mbggenerated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
}