package com.iwhalecloud.byai.state.domain.chat.model;

import java.util.Date;

public class ByaiAimodel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.model_id
     *
     * @mbggenerated
     */
    private Long modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.model_type
     *
     * @mbggenerated
     */
    private String modelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.model
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.auth_token
     *
     * @mbggenerated
     */
    private String authToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.status
     *
     * @mbggenerated
     */
    private String status;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.create_time
     *
     * @mbggenerated
     */
    private Date createTime;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.is_support_chart
     *
     * @mbggenerated
     */
    private String isSupportChart;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.max_content_token
     *
     * @mbggenerated
     */
    private Long maxContentToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byai_aimodel.is_deepthink
     *
     * @mbggenerated
     */
    private String isDeepthink;

   /**
    * 入参配置--传给python
    * */
    private String inParams;

    public Long getModelId() {
        return modelId;
    }

    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    public String getModelType() {
        return modelType;
    }

    public void setModelType(String modelType) {
        this.modelType = modelType;
    }

    public String getModelName() {
        return modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getModelNo() {
        return modelNo;
    }

    public void setModelNo(String modelNo) {
        this.modelNo = modelNo;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getAuthToken() {
        return authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getCreateBy() {
        return createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getIsSupportChart() {
        return isSupportChart;
    }

    public void setIsSupportChart(String isSupportChart) {
        this.isSupportChart = isSupportChart;
    }

    public Long getMaxContentToken() {
        return maxContentToken;
    }

    public void setMaxContentToken(Long maxContentToken) {
        this.maxContentToken = maxContentToken;
    }

    public String getIsDeepthink() {
        return isDeepthink;
    }

    public void setIsDeepthink(String isDeepthink) {
        this.isDeepthink = isDeepthink;
    }

    public String getInParams() {
        return inParams;
    }

    public void setInParams(String inParams) {
        this.inParams = inParams;
    }
}