apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: byclaw-artifacts
  namespace: by-service
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
