apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: byclaw-workspace
  namespace: by-sandbox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
